# SPDX-License-Identifier: MIT-0
---
# tasks file for rhel_security_access
- name: Remove default local admin account
  ansible.builtin.include_tasks:
    file: remove_default_admin.yml

- name: Add AD domain user group as admin
  ansible.builtin.include_tasks:
    file: add_group_admin.yml
