# SPDX-License-Identifier: MIT-0
---
# defaults file for rhel_rhsm
capsule_hostname: "capsule-lb.manmandes.example.com"
rhsm_baseurl: "https://capsule-lb.manmandes.example.com/pulp/content"
sat_env: azure