# SPDX-License-Identifier: MIT-0
---
# defaults file for rhel_crowdstrike
falcon_cid: "{{ lookup('env', 'FALCON_CID') }}"
falcon_apd: "{{ lookup('env', 'FALCON_APD') | default(false) }}"
falcon_aph: "{{ lookup('env', 'FALCON_APH') | default(omit) }}"
falcon_app: "{{ lookup('env', 'FALCON_APP') | default(omit) }}"
falcon_tags: "{{ lookup('env', 'FALCON_TAGS') | default(omit) }}"
falcon_message_log: "{{ lookup('env', 'FALCON_MESSAGE_LOG') | default(true) }}"
