# SPDX-License-Identifier: MIT-0
---
# tasks file for rhel_crowdstrike
- name: Check CrowdStrike tags
  ansible.builtin.command:
    cmd: /opt/CrowdStrike/falconctl -g --tags
  register: tags_check
  changed_when: false

- name: Configure Crowdstrik
  when: tags_check.stdout is not defined
  ansible.builtin.include_role:
    crowdstrike.falcon.falcon_configure
  vars:
    falcon_cid: "{{ falcon_cid }}"
    falcon_apd: "{{ falcon_apd | default(false) }}"
    falcon_aph: "{{ falcon_aph | default(omit) }}"
    falcon_app: "{{ falcon_app | default(omit) }}"
    falcon_tags: "{{ falcon_tags | default(omit) }}"
    falcon_message_log: "{{ falcon_message_log | default(true) }}"


