# SPDX-License-Identifier: MIT-0
---
# tasks file for rhel_crowdstrike
- name: Set package name
  ansible.builtin.set_fact:
    package_name: falcon-sensor

- name: Include install tasks
  ansible.builtin.include_tasks:
    file: install.yml

- name: Include configure tasks
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Include service tasks
  ansible.builtin.include_tasks:
    file: service.yml
