#SPDX-License-Identifier: MIT-0
---
# defaults file for rhel_clean
logfiles:
  - '/var/log/audit/audit.log'
  - '/var/log/cron'
  - '/var/log/maillog'
  - '/var/log/messages'
  - '/var/log/secure'
  - '/var/log/spooler'
  - '/var/log/wtmp'
  - '/var/log/btmp'
  - '/var/log/lastlog'
  - '/var/log/faillog'
  - '/var/log/tallylog'
  - '/root/.bash_history'
  - '/root/.firstboot.log'
  - '/root/anaconda-ks.cfg'
  - '/root/.cache'
  - '/root/.local'
