# SPDX-License-Identifier: MIT-0
---
# tasks file for rhel_package_install
- name: Package install
  ansible.builtin.dnf:
    state: present
    name:
      - "@minimal-environment"
      - adcli
      - authselect
      - realmd
      - krb5-workstation
      - python3-dnf-plugin-versionlock
      - NetworkManager-dispatcher-routing-rules
