# SPDX-License-Identifier: MIT-0
---
- name: Unregister redhat satellite
  community.general.redhat_subscription:
    username: "{{ sat_username }}"
    password: "{{ sat_password }}"
    server_hostname: "{{ capsule_hostname }}"
    rhsm_baseurl: "{{ capsule_url }}"
    state: absent
